[workspace]
members = [
    "node",
    "pallets/asset",
    "pallets/market",
    "pallets/trading-account",
    "pallets/trading-fees",
    "pallets/support",
    "pallets/sync-facade",
    "runtime",
]
[profile.release]
panic = "unwind"
