[toolchain]
channel = "nightly-2024-01-30"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt",
]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"