---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l3-front
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: l3-front
  replicas: 1
  template:
    metadata:
      labels:
        app: l3-front
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
      - name: app
        env:
        - name: WS_URL
          {{ if eq .Values.env "sandbox" }}
          value: "wss://l3.{{ .Values.env }}.zkx.fi"
          {{ else if eq .Values.env "sandbox-2" }}
          value: "wss://l3.{{ .Values.env }}.zkx.fi"
          {{ else if eq .Values.env "stage" }}
          value: "wss://l3.{{ .Values.env }}.zkx.fi"
          {{ else }}
          value: "wss://l3.{{ .Values.env }}.k8s.ntwrkx.com"
          {{ end }}
        image: jacogr/polkadot-js-apps:latest  
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      nodeSelector:
        role: worker-spot