---
apiVersion: v1
kind: Service
metadata:
  name: l3-front
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
  selector:
    app: l3-front