apiVersion: v1
kind: Service
metadata:
  name: l3-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: substrate-node
    # app.kubernetes.io/component: validator-node ## for sandbox-2 and stage
    
  ports:
    - protocol: TCP
      port: 9944
      targetPort: 9944
