{{ $fullname :=  include "node.fullname" . }}
{{ if .Values.node.persistGeneratedNodeKey }}
{{ else if .Values.node.customNodeKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-custom-node-key
data:
  custom-node-key: {{ .Values.node.customNodeKey | b64enc }}
{{ end }}