name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build_base:
    runs-on: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, 'drop_data') }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.base -t zkxteam/zkxsubstrate:stage-base .
      - run: docker push zkxteam/zkxsubstrate:stage-base

  build_node:
    runs-on: [ubuntu-latest]
    needs: [build_base]
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.node -t zkxteam/zkxsubstrate:stage-node .
      - run: docker push zkxteam/zkxsubstrate:stage-node

  build_runtime:
    runs-on: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, 'drop_data') || contains(github.event.head_commit.message, 'runtime_update') }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.update --build-arg "SCRIPT_NAME=stage.ts" -t zkxteam/zkxsubstrate:stage-runtime .
      - run: docker push zkxteam/zkxsubstrate:stage-runtime


  deploy_with_drop:
    runs-on: [ubuntu-latest]
    needs: ['build_node']
    container:
      image: alpine/k8s:1.23.16
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v1
    - run: aws eks update-kubeconfig --region eu-north-1 --name dev
    - run: helm uninstall zkxl3-main -n zkxl3-stage
    - run: helm uninstall zkxl3-follower -n zkxl3-stage
    - run: kubectl get pvc -n zkxl3-stage | grep -v NAME | awk '{print $1}' | xargs -I {} kubectl delete pvc {} -n zkxl3-stage --force
    - run: helm upgrade -i root .helm/root/ -f .helm/root/values.yml -n zkxl3-stage --set dockerhub_token=${{ secrets.DOCKERHUB_TOKEN_K8S }} --wait --atomic --timeout 600s --create-namespace
    - run: helm upgrade -i zkxl3-main .helm/l3/ -f .helm/l3/values-main-stage.yml -n zkxl3-stage --wait --atomic --timeout 600s
    - run: helm upgrade -i zkxl3-follower .helm/l3/ -f .helm/l3/values-follower-stage.yml -n zkxl3-stage --wait --atomic --timeout 600s


  runtime_update:
    runs-on: [ubuntu-latest]
    needs: ['build_runtime']
    if: ${{ contains(github.event.head_commit.message, 'runtime_update') }}
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker run zkxteam/zkxsubstrate:stage-runtime

  runtime_update_when_drop:
    runs-on: [ubuntu-latest]
    needs: ['build_runtime', 'deploy_with_drop']
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker run zkxteam/zkxsubstrate:stage-runtime