name: Deploy

on:
  push:
    branches:
      - infra

# jobs:
#   build:
#     runs-on: [ubuntu-latest]
#     steps:
#       - uses: actions/checkout@v1
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - run: docker build -t zkxteam/zkxsubstrate:stand2 .
#       - run: docker push zkxteam/zkxsubstrate:stand2


  deploy:
    runs-on: [ubuntu-latest]
    # needs: ['build']
    container:
      image: alpine/k8s:1.23.16
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v1
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - run: aws eks update-kubeconfig --region eu-north-1 --name dev
    - run: helm upgrade -i root .helm/root/ -f .helm/root/values.yml -n zkxl3-stand-2 --set dockerhub_token=${{ secrets.DOCKERHUB_TOKEN_K8S }} --wait --atomic --timeout 600s --create-namespace
    - run: helm upgrade -i zkxl3-main .helm/l3/ -f .helm/l3/values-main-stand-2.yml -n zkxl3-stand-2 --wait --atomic --timeout 600s
    - run: helm upgrade -i zkxl3-follower .helm/l3/ -f .helm/l3/values-follower-stand-2.yml -n zkxl3-stand-2 --wait --atomic --timeout 600s
    - run: helm upgrade -i zkxl3-front  .helm/l3-front/ -f .helm/l3-front/values-stand-2.yml -n zkxl3-stand-2 --wait --atomic --timeout 300s
