name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build_base:
    runs-on: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, 'stand_2') && contains(github.event.head_commit.message, 'drop_data') }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.base -t zkxteam/zkxsubstrate:stand4-base .
      - run: docker push zkxteam/zkxsubstrate:stand4-base

  build_node:
    runs-on: [ubuntu-latest]
    needs: [build_base]
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.node -t zkxteam/zkxsubstrate:stand4-node .
      - run: docker push zkxteam/zkxsubstrate:stand4-node

  build_runtime:
    runs-on: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, 'stand_4') && contains(github.event.head_commit.message, 'runtime_update') }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.update --build-arg "SCRIPT_NAME=stand-4.ts" -t zkxteam/zkxsubstrate:stand4-runtime .
      - run: docker push zkxteam/zkxsubstrate:stand4-runtime

  deploy_with_drop:
    runs-on: [ubuntu-latest]
    needs: ['build_node']
    container:
      image: alpine/k8s:1.23.16
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v1
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - run: aws eks update-kubeconfig --region eu-north-1 --name dev
    - run: helm uninstall zkxl3-main -n zkxl3-stand-4
    - run: helm uninstall zkxl3-follower -n zkxl3-stand-4
    - run: helm upgrade -i root .helm/root/ -f .helm/root/values.yml -n zkxl3-stand-4 --set dockerhub_token=${{ secrets.DOCKERHUB_TOKEN_K8S }} --wait --atomic --timeout 600s --create-namespace
    - run: helm upgrade -i zkxl3-main .helm/l3/ -f .helm/l3/values-main-stand-4.yml -n zkxl3-stand-4 --wait --atomic --timeout 600s
    - run: helm upgrade -i zkxl3-follower .helm/l3/ -f .helm/l3/values-follower-stand-4.yml -n zkxl3-stand-4 --wait --atomic --timeout 600s

  runtime_update:
    runs-on: [ubuntu-latest]
    needs: ['build_runtime']
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker run zkxteam/zkxsubstrate:stand4-runtime