name: Deploy

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, 'stand_1') && contains(github.event.head_commit.message, 'drop_data') }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.node -t zkxteam/zkxsubstrate:stand1-node .
      - run: docker push zkxteam/zkxsubstrate:stand1-node

  build_runtime:
    runs-on: [ubuntu-latest]
    if: ${{ contains(github.event.head_commit.message, 'stand_1') && contains(github.event.head_commit.message, 'runtime_update') }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f Dockerfile.update --build-arg "SCRIPT_NAME=stand-1.ts" -t zkxteam/zkxsubstrate:stand1-runtime .
      - run: docker push zkxteam/zkxsubstrate:stand1-runtime

  deploy_with_drop:
    runs-on: [ubuntu-latest]
    needs: ['build']
    container:
      image: alpine/k8s:1.23.16
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v1
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - run: aws eks update-kubeconfig --region eu-north-1 --name dev
    - run: helm uninstall zkxl3-main -n zkxl3-stand-1
    - run: helm uninstall zkxl3-follower -n zkxl3-stand-1
    - run: kubectl get pvc -n zkxl3-stand-1 | grep -v NAME | awk '{print $1}' | xargs -I {} kubectl delete pvc {} -n zkxl3-stand-1 --force
    - run: helm upgrade -i root .helm/root/ -f .helm/root/values.yml -n zkxl3-stand-1 --set dockerhub_token=${{ secrets.DOCKERHUB_TOKEN_K8S }} --wait --atomic --timeout 600s --create-namespace
    - run: helm upgrade -i zkxl3-main .helm/l3/ -f .helm/l3/stand1-main-values.yml -n zkxl3-stand-1 --wait --atomic --timeout 600s
    - run: helm upgrade -i zkxl3-follower .helm/l3/ -f .helm/l3/stand1-follower-values.yml -n zkxl3-stand-1 --wait --atomic --timeout 600s
    - run: helm upgrade -i zkxl3-front .helm/l3-front/ -f .helm/l3-front/stand1-values.yml -n zkxl3-stand-1


  runtime_update:
    runs-on: [ubuntu-latest]
    needs: ['build_runtime']
    if: ${{ contains(github.event.head_commit.message, 'stand_1') && contains(github.event.head_commit.message, 'runtime_update') }}
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker run zkxteam/zkxsubstrate:stand1-runtime